version: '3'
services:
  backend:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb

volumes:
  mongo-data:
